version: "2.1"

services:
  # production container
  app_parking_lot_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: parking-lot-api:1.0.0
    container_name: ctn_parking_lot_api
    restart: always
    working_dir: /usr/src/app
    command: >
      sh -c "npx sequelize db:create &&
             npx sequelize db:migrate &&
             node server.js"
    ports:
      - 5005:5005
    links:
      - db_mysql
    environment:
      - PORT=5005
      - DEBUG=parking-lot-api:*
      - SECRET=meow
      - DB_HOST=db_mysql
      - DB_NAME=parking_lot_api
      - DB_USERNAME=root
      - DB_PASSWORD=rootpass
      - DB_PORT=3306
    depends_on:
      db_mysql:
        condition: service_healthy
  
  # alpha / develop container for testing purpose
  app_parking_lot_api_alpha:
    build:
      context: .
      dockerfile: Dockerfile.alpha
    image: parking-lot-api:1.0.0-alpha
    container_name: ctn_parking_lot_api_alpha
    restart: always
    working_dir: /usr/src/app
    command: >
      sh -c "npx sequelize db:create &&
             npx sequelize db:migrate &&
             node server.js"
    ports:
      - 5006:5005
    links:
      - db_mysql
    environment:
      - PORT=5005
      - DEBUG=parking-lot-api:*
      - SECRET=meow
      - DB_HOST=db_mysql
      - DB_NAME=parking_lot_api_alpha
      - DB_USERNAME=root
      - DB_PASSWORD=rootpass
      - DB_PORT=3306
    depends_on:
      db_mysql:
        condition: service_healthy

  db_mysql:
    image: mysql:8.0.19
    container_name: ctn_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=joe
      - MYSQL_PASSWORD=joepass
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
